### ISSUE TITLE
Next UI support

### ISSUE THREAD

**Issue by ahmed0x77** [jekigates/nextron-tailwind-shadcn-template#1]
Thank you very much for Nextron with Shadcn UI. 
Could you make Nextron with Next UI ?
Many people are looking for that but we can't find it.

**Comment by jekigates** [comment]
> Thank you very much for Nextron with Shadcn UI. Could you make Nextron with Next UI ? Many people are looking for that but we can't find it.

I'm new to NextUI, but I've been diving in after your comment inspired me! I've already set up path aliases using the "@" symbol and implemented theming. There's a lot more to explore, and I'm excited to learn further. Check out my Nextron project with NextUI here: https://github.com/jekigates/nextron-with-next-ui.git

**Comment by ahmed0x77** [comment]
Thank you so much for the quick response!, that was super fast man!
I'll be sharing [nextron-with-next-ui] with everyone. Keep up the great work! 🙌
